# ==============================================================================
# Configuracao Centralizada: Eureka Server (Service Registry & Discovery)
# ==============================================================================
server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # O Eureka Server e o proprio registro, portanto nao se registra nem busca registro
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Endpoints de monitoramento e integridade
management:
  endpoints:
    web:
      exposure:
        include: health, info
